/** A small navigation shell around the unmodified, same-origin vendor Studio. */
export const studioWorkspaceHtml=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Studio workspace | Sbarbase</title><link rel="stylesheet" href="/__sbarbase/workspace.css"><script src="/__sbarbase/workspace.js" defer></script></head><body><header aria-label="Workspace navigation"><a id="console" aria-label="Back to Sbarbase console">sbarbase</a><span class="divider" aria-hidden="true">/</span><label><span class="sr-only">Organization</span><select id="organization" aria-label="Organization" disabled></select></label><span class="divider" aria-hidden="true">/</span><label><span class="sr-only">Project</span><select id="project" aria-label="Project" disabled></select></label><span class="divider" aria-hidden="true">/</span><label><span class="sr-only">Environment</span><select id="environment" aria-label="Environment" disabled></select></label><span id="state" class="badge"></span><button id="open" disabled>Open Studio</button><button id="refresh" aria-label="Refresh workspace">Refresh</button></header><div id="status" role="status">Loading workspace…</div><main><iframe id="studio" title="Supabase Studio" allow="clipboard-read; clipboard-write"></iframe><div id="pending" hidden>Select a running environment and choose Open Studio.</div></main></body></html>`;

export const studioWorkspaceCss=`:root{color-scheme:light dark;font:12px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--page:#fafafa;--surface:#fff;--border:#e4e4e7;--text:#18181b;--muted:#666;--accent:#3ecf8e}*{box-sizing:border-box}body{margin:0;background:var(--page);color:var(--text);height:100dvh;display:flex;flex-direction:column}header{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid var(--border);background:var(--surface);flex-shrink:0}a{color:inherit;text-decoration:none;font-weight:600;cursor:pointer}select,button{font:inherit;color:inherit;border:1px solid var(--border);border-radius:6px;background:var(--surface);height:28px;padding:3px 8px;min-width:0}select{max-width:220px;cursor:pointer}button{cursor:pointer;white-space:nowrap}button:disabled,select:disabled{opacity:.5;cursor:default}button:hover:enabled{background:var(--page)}button#open:enabled{background:var(--accent);color:#062518;border-color:var(--accent)}a:focus-visible,button:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.divider{color:var(--muted)}.badge{font-size:10px;letter-spacing:.05em;text-transform:uppercase;color:var(--muted);margin-left:auto}.sr-only{position:absolute;width:1px;height:1px;clip-path:inset(50%);overflow:hidden;white-space:nowrap}#status{padding:5px 12px;color:var(--muted);border-bottom:1px solid var(--border)}#status:empty{display:none}main{position:relative;flex:1;min-height:0}iframe{display:block;width:100%;height:100%;border:0}#pending{position:absolute;inset:0;padding:40px;text-align:center;background:var(--page);color:var(--muted)}#pending[hidden]{display:none}body[data-pending] iframe{visibility:hidden}@media(prefers-color-scheme:dark){:root{--page:#171717;--surface:#1c1c1c;--border:#303030;--text:#ededed;--muted:#a0a0a0}}@media(max-width:720px){header{flex-wrap:wrap;gap:6px}header>a{width:100%}header label{flex:1;min-width:90px}select{width:100%;max-width:none;height:34px}button{height:34px}.divider{display:none}.badge{margin-left:0}#pending{padding:24px}}`;

export const studioWorkspaceJs=`'use strict';
const org=document.getElementById('organization'),project=document.getElementById('project'),environment=document.getElementById('environment'),open=document.getElementById('open'),refresh=document.getElementById('refresh'),status=document.getElementById('status'),state=document.getElementById('state'),frame=document.getElementById('studio'),pending=document.getElementById('pending');
let data,controller,sequence=0,busy=false;
function options(select,rows,selected){select.replaceChildren();for(const row of rows){const item=document.createElement('option');item.value=row.id;item.textContent=row.name;select.append(item);}select.value=selected||'';select.disabled=busy||!rows.length;}
function update(message=true){const valid=org.value===data?.selection.organization&&project.value===(data?.selection.project||'');const target=valid?data?.environments.find(row=>row.id===environment.value):undefined;const current=target?.id===data?.current.environment.id&&org.value===data?.current.organization.id&&project.value===data?.current.project.id;const running=!!target&&target.ready&&target.state==='running';state.textContent=target?(target.ready?target.state:'Not provisioned'):'';open.disabled=busy||!running||current;open.textContent=current?'Current Studio':'Open Studio';pending.hidden=current||!data;document.body.toggleAttribute('data-pending',!!data&&!current);if(message&&data&&!current&&!busy)status.textContent=running?'Choose Open Studio to switch to this environment.':'Studio is not running here. Start it from the console, then Refresh.';}
function controls(){for(const select of [org,project,environment])select.disabled=busy||!select.options.length;refresh.disabled=busy;update(false);}
async function responseValue(response){if(response.status===401||response.status===403){data=undefined;frame.removeAttribute('src');for(const select of [org,project,environment])select.replaceChildren();throw new Error(response.status===401?'Your Studio session ended. Open Studio from the console to sign in again.':'This selection is no longer available. Refresh to reload your projects.');}return response.json();}
async function load(organization,selectedProject){const id=++sequence;controller?.abort();controller=new AbortController();busy=true;controls();status.textContent='Loading workspace…';const params=new URLSearchParams();if(organization)params.set('organization',organization);if(selectedProject)params.set('project',selectedProject);try{const response=await fetch('/__sbarbase/navigation?'+params,{credentials:'same-origin',cache:'no-store',signal:controller.signal});const value=await responseValue(response);if(!response.ok)throw new Error(value.message||'Unable to load workspace.');if(id!==sequence)return;data=value;options(org,data.organizations,data.selection.organization);options(project,data.projects,data.selection.project);const selected=data.environments.some(row=>row.id===data.current.environment.id)?data.current.environment.id:data.environments[0]?.id;options(environment,data.environments,selected);const consoleUrl=new URL(data.consoleUrl);if(['http:','https:'].includes(consoleUrl.protocol))document.getElementById('console').href=consoleUrl.href;document.title=data.current.organization.name+' / '+data.current.project.name+' / '+data.current.environment.name+' | Studio';if(!frame.getAttribute('src'))frame.src='/project/default/editor';status.textContent='';}catch(error){if(id===sequence&&error.name!=='AbortError')status.textContent=error instanceof TypeError?'Unable to reach server. Choose Refresh to try again.':error.message;}finally{if(id===sequence){busy=false;controls();}}}
org.addEventListener('change',()=>{project.replaceChildren();environment.replaceChildren();load(org.value);});project.addEventListener('change',()=>load(org.value,project.value));environment.addEventListener('change',()=>update());refresh.addEventListener('click',()=>load(org.value,project.value));
open.addEventListener('click',async()=>{const target=data?.environments.find(row=>row.id===environment.value);if(busy||!target?.ready||target.state!=='running')return;busy=true;controls();status.textContent='Opening Studio…';try{const response=await fetch('/__sbarbase/switch',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({environment:target.id})});const value=await responseValue(response);if(!response.ok)throw new Error(value.message||'Unable to switch Studio.');const next=new URL(value.href,location.href);if(next.protocol!==location.protocol||next.port!==location.port||!/^([a-f0-9]{24}\\.studio\\.localhost|127\\.0\\.0\\.1)$/.test(next.hostname)||!next.pathname.startsWith('/__sbarbase/'))throw new Error('Invalid Studio destination.');location.assign(next.href);}catch(error){status.textContent=error instanceof TypeError?'Unable to reach server. Choose Refresh to try again.':error.message;}finally{busy=false;controls();}});
load();`;

export function studioWorkspaceAsset(path:string):Response|undefined {
 const asset=path==='/__sbarbase/workspace'?{body:studioWorkspaceHtml,type:'text/html; charset=utf-8'}:
  path==='/__sbarbase/workspace.css'?{body:studioWorkspaceCss,type:'text/css; charset=utf-8'}:
  path==='/__sbarbase/workspace.js'?{body:studioWorkspaceJs,type:'text/javascript; charset=utf-8'}:undefined;
 if(!asset)return;
 return new Response(asset.body,{headers:{'content-type':asset.type,'cache-control':'no-store','x-content-type-options':'nosniff',
  'content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; frame-src 'self'; frame-ancestors 'none'; object-src 'none'; base-uri 'none'; form-action 'self'",'referrer-policy':'no-referrer'}});
}
